apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ravi-app
  name: ravi-internal-lb
  namespace: ravi-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ravi-app
status:
  loadBalancer: {}
